// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pdf} from '../models';
import {frontend} from '../models';

export function GetUrls(arg1:string):Promise<Array<pdf.ExportURL>>;

export function Greet(arg1:string):Promise<string>;

export function OpenDirectoryDialog(arg1:frontend.OpenDialogOptions):Promise<string>;

export function PrintPDF(arg1:string):Promise<pdf.ExportPdf>;

export function ReadDirByPath(arg1:string):Promise<Array<string>>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function SaveFile(arg1:string,arg2:Array<number>):Promise<boolean>;

export function SaveFileByString(arg1:string,arg2:string):Promise<boolean>;

export function SaveFileDialog(arg1:frontend.SaveDialogOptions):Promise<string>;
