// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUrls(arg1) {
  return window['go']['main']['App']['GetUrls'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['main']['App']['OpenDirectoryDialog'](arg1);
}

export function PrintPDF(arg1) {
  return window['go']['main']['App']['PrintPDF'](arg1);
}

export function ReadDirByPath(arg1) {
  return window['go']['main']['App']['ReadDirByPath'](arg1);
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveFileByString(arg1, arg2) {
  return window['go']['main']['App']['SaveFileByString'](arg1, arg2);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}
